# Generated by Django 4.0.2 on 2022-08-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='fullname', max_length=100),
            preserve_default=False,
        ),
    ]
